jaffle_shop_metrics-bigquery-db:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: oauth-secrets
      project: ada2025-450217
      dataset: jaffle_shop
      threads: 2
      token: ya29.c.c0ASRK0GbSzReZKenZMnHyljWgx8Sx1XQVw7WFXilIvhZwKAJ5eePt_eTVinJYO10Fk2nK_P2_oRzkxz7-AF74bUoN3k-7UEk-BnZCzxKnF-gXtqW8L6decU-P5g3cZ-WG9HpqwTMTtMj55UC4NxYMBcfkt8bisCYzYqP9S7NmY5Nd9WaBfe6d56FUK4RiHn7b0vzWHqB8WFDGz7EunBpE_YNjcUzpH-phn_L-DNQ7IYdQTjVqh-em6uvgK5xp8PBq3QYKymyYZsSKXCWxAPBT_ay1db7ozeFteeGjkgeIqxokQmvneS8OTEP_RkwzubxtaZFBKxkJrxaEm7CB35yuPTbGhqA3ciIvo84G8jMzfQAOBOvzaZB2CfPkOP0jbewDhv8T15h_PbUOK7h49WvhZhwG416C4Fc-em0jW-cBQvs7xavX3_4V3sozyrUgw4sykeww2q_Xnz9vU6okVO4cFdJUJ-lx2guYc2_z21cXvaZzwdk-VF60iWkbRFIU4wYnUyMRyOyMM4behrIbRk2JmI9pZ1i7-Ic-u2lvpygJskkbnd17padRzpyh47VXI0jt41XsayFIS68yQrlMob0WMORisOM9fkW8ukFdrR8e7h5m6nXJWJhgBBbaxXeayqx-h9z0I0v2g8cmus3M-a5IfU4bzzrRmesWbg2gUfQe3RzxmshaXu7kVxp8YXkiBmUXO4c6ycfXZkR7rUrXcO68yMmf48c0vdRpFUVpW2IFW1j664J2Iih_x0ruIF6vvu1gFb-jq35oiQ5havhfWegmwynz8qVM3zVtYjtZ5bXlk1oy1pol02gm-pe8cFhgpny9jSZMmW_JOq_iZ8_jOnaudwWkgw2gX-zV_lRj9o0Sps5taeSQqiok_4X9r182p4XvSkJs5F82M96ZwYsZVcx3Fq95oo7_k13xj7hej0MqIZMe6cmg8Rix8r_ace6F0iXqR4V75S6JWS7pXpt31wkStX06rj7taI1UB0rfzw_S0sY-RqWznpiI8-7
